### ISSUE TITLE
animation reel position on beercamp

### ISSUE THREAD

**Issue by imjared** [nclud/sketchbook#12]
So it's running fine, it just seems to be in the wrong position and not fixed. This was definitely an issue I introduced but I'm having trouble figuring out what happened between 937a05aebae35d39ca7fa0cabad536e0de477319 and 35335130e0e8597d5db4ac348ff59f16b03e15a2 to cause this issue.

I'm almost certain it's CSS related.

**update:** can see on `#design` that the `top` property is not updating. not sure where that's happening in beercamp.js or if that's part of skrollr.

**Comment by kyleconrad** [comment]
As part of the changes I made yesterday, I removed the "top" element from desktop devices and simply relied on classes to set the fixed position (inside basecamp-design and basecamp-dev) - this sets the .skrollable-between class to fixed on scrolling (since Skrollr adjusting the top property didn't work and caused stuttering).

Looks like those CSS classes didn't carry over - latest commit should have those changes.
