### ISSUE TITLE
Entire site on touch devices

### ISSUE THREAD

**Issue by kyleconrad** [nclud/sketchbook#22]
Somehow the entire site doesn't work right now on mobile/tablet - I'm assuming it's related to one of the recent changes made along the way but no idea what (not getting any errors in console or what not).

It looks like Skrollr works on the header section - logo scales, all that good stuff.

As soon as you get past the header, skrollr stops working entirely - no menu drop down, no firing of other scroll events at any other point.

**Comment by imjared** [comment]
Nice! On a quick glance, it looks like we'll still want to attach those to the global `bc` object, eventually so we don't pollute the global scope.

_Update_: We also should keep beercamp-specific vars in beercamp.js since, presumably, each case study will have it's own scripts. If there are items we're going to need everywhere, we should create a utility class for sketchbook in general.
